services:
  node:
    build:
      context: .
      dockerfile: docker/node.dockerfile
    container_name: dev_marshmello_node
    entrypoint: "tail -f /dev/null"
    image: marshmello/node
    labels:
      caddy_0: marshmello.aaa
      caddy_0.tls: internal
      caddy_0.reverse_proxy: '{{upstreams 5173}}'
      caddy_1: api.marshmello.aaa
      caddy_1.tls: internal
      caddy_1.reverse_proxy: '{{upstreams 3333}}'
    restart: unless-stopped
    networks:
      - "default"
      - "global_reverse_proxy"
    volumes:
      - ./:/home/node/app
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /home/node/app

  database:
    build:
      context: .
      dockerfile: docker/postgres.dockerfile
    container_name: dev_marshmello_postgres
    image: marshmello/postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: password
      POSTGRES_DB: marshmello
    networks:
      - "default"
    volumes:
      -  postgres_data:/var/lib/postgresql/data

  database_test:
    build:
      context: .
      dockerfile: docker/postgres.dockerfile
    container_name: test_marshmello_postgres
    image: marshmello/postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: password
      POSTGRES_DB: marshmello
    networks:
      - "default"
    volumes:
      -  postgres_test_data:/var/lib/postgresql/data

  adminer:
    container_name: dev_marshmello_adminer
    image: adminer:latest
    restart: unless-stopped
    labels:
      caddy: db.marshmello.aaa
      caddy.tls: internal
      caddy.reverse_proxy: "{{upstreams 8080}}"
    networks:
      - "default"
      - "global_reverse_proxy"

  mailer:
    container_name: dev_marshmello_mailer
    image: maildev/maildev
    labels:
      caddy: mailer.marshmello.aaa
      caddy.tls: internal
      caddy.reverse_proxy: "{{upstreams 1080}}"
    networks:
      - "default"
      - "global_reverse_proxy"
    restart: unless-stopped

networks:
  default:
    driver: bridge
    name: dev_net_marshmello_default
  global_reverse_proxy:
    external: true
volumes:
  postgres_data:
    name: dev_vol_marshmello_pg
  postgres_test_data:
    name: test_vol_marshmello_pg
